// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroes.Data;

#nullable disable

namespace Super_Heroes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231002192844_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHeroes.Models.Superhero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComicUniverse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179"),
                            ComicUniverse = "DC",
                            Description = "Last Son of Krypton with superhuman strength and more.",
                            Name = "Superman",
                            RealName = "Clark Kent"
                        });
                });

            modelBuilder.Entity("SuperHeroes.Models.Superpower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperPower")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4343990-7ebe-4bfe-8aac-8dcae3061ca1"),
                            Description = "Superhuman speed is the ability to move, react, and operate at speeds far beyond those of ordinary humans. Individuals with this power can run, fly, or perform any physical activity at velocities that exceed the capabilities of normal human beings. This power often grants the user enhanced reflexes, allowing them to perceive and react to events in the blink of an eye. Superhuman speed is a versatile ability, useful in combat, rescue missions, and various other situations.",
                            SuperPower = "Superhuman Speed",
                            SuperheroId = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179")
                        },
                        new
                        {
                            Id = new Guid("679ff9a1-0b17-454e-8976-38b6251f199e"),
                            Description = "Heat vision is a superpower that allows an individual to emit beams of intense heat and energy from their eyes. This ability enables the user to generate focused beams that can reach extremely high temperatures, capable of melting or vaporizing objects. Heat vision is often depicted as red or orange beams that emanate from the eyes. Characters with this power can use it for offensive purposes, such as attacking adversaries, and for practical applications like welding or cutting through obstacles.",
                            SuperPower = "Heat Vision",
                            SuperheroId = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179")
                        },
                        new
                        {
                            Id = new Guid("26b1e5a2-8d28-464b-b49d-ce6fe021ccb6"),
                            Description = "Super hearing is a heightened auditory ability that allows individuals to perceive sounds at frequencies and volumes beyond the normal human range. Characters with super hearing can detect faint sounds from great distances, hear frequencies outside the human spectrum, and focus on specific sounds amidst background noise. This power grants users an extraordinary level of situational awareness, making them adept at eavesdropping, detecting hidden threats, and responding to emergencies based on auditory cues. Super hearing is a valuable asset in crime-fighting and surveillance.",
                            SuperPower = "Super Hearing",
                            SuperheroId = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179")
                        });
                });

            modelBuilder.Entity("SuperHeroes.Models.Villain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Villains");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37213080-c2bd-4314-a0e9-735ec6d6712f"),
                            Background = "A brilliant and wealthy businessman who despises Superman",
                            Name = "Lex Luthor",
                            SuperheroId = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179")
                        },
                        new
                        {
                            Id = new Guid("3503f8ed-52ec-442a-85a3-92b3dfc4914d"),
                            Background = "A Kryptonian military leader with superhuman abilities similar to Superman. Zod seeks to establish Kryptonian dominance on Earth and considers Superman an obstacle.",
                            Name = "General Zod",
                            SuperheroId = new Guid("25bf6212-9051-45f4-aced-88b0b3cb6179")
                        });
                });

            modelBuilder.Entity("SuperHeroes.Models.Superpower", b =>
                {
                    b.HasOne("SuperHeroes.Models.Superhero", "Superhero")
                        .WithMany("Superpowers")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("SuperHeroes.Models.Villain", b =>
                {
                    b.HasOne("SuperHeroes.Models.Superhero", "Superhero")
                        .WithMany("Villains")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("SuperHeroes.Models.Superhero", b =>
                {
                    b.Navigation("Superpowers");

                    b.Navigation("Villains");
                });
#pragma warning restore 612, 618
        }
    }
}
